export * from './achievements.service';
import { AchievementsService } from './achievements.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './bills.service';
import { BillsService } from './bills.service';
export * from './directories.service';
import { DirectoriesService } from './directories.service';
export * from './incidents.service';
import { IncidentsService } from './incidents.service';
export * from './logNotes.service';
import { LogNotesService } from './logNotes.service';
export * from './students.service';
import { StudentsService } from './students.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AchievementsService, AuthenticationService, BillsService, DirectoriesService, IncidentsService, LogNotesService, StudentsService, TasksService, UsersService];
