export * from './achievements.service';
import { AchievementsService } from './achievements.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './bills.service';
import { BillsService } from './bills.service';
export * from './directories.service';
import { DirectoriesService } from './directories.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './houses.service';
import { HousesService } from './houses.service';
export * from './incidents.service';
import { IncidentsService } from './incidents.service';
export * from './logNotes.service';
import { LogNotesService } from './logNotes.service';
export * from './regGroups.service';
import { RegGroupsService } from './regGroups.service';
export * from './schools.service';
import { SchoolsService } from './schools.service';
export * from './students.service';
import { StudentsService } from './students.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './yearGroups.service';
import { YearGroupsService } from './yearGroups.service';
export const APIS = [AchievementsService, AuthenticationService, BillsService, DirectoriesService, DocumentsService, HousesService, IncidentsService, LogNotesService, RegGroupsService, SchoolsService, StudentsService, TasksService, UsersService, YearGroupsService];
