/**
 * MyPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressModel } from './addressModel';
import { AgencyTypeModel } from './agencyTypeModel';
import { DirectoryModel } from './directoryModel';

export interface AgencyModel { 
    id?: string;
    typeId?: string;
    addressId?: string;
    directoryId?: string;
    name?: string;
    website?: string;
    deleted?: boolean;
    agencyType?: AgencyTypeModel;
    address?: AddressModel;
    directory?: DirectoryModel;
}