/**
 * MyPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DirectoryModel } from './directoryModel';
import { UserModel } from './userModel';

export interface BulletinModel { 
    id?: string;
    directoryId?: string;
    authorId?: string;
    createDate?: Date;
    expireDate?: Date;
    title: string;
    detail: string;
    staffOnly?: boolean;
    approved?: boolean;
    author?: UserModel;
    directory?: DirectoryModel;
}