/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CalendarEventModel { 
    id?: string;
    allDay?: boolean;
    start?: Date;
    end?: Date;
    title?: string;
    url?: string;
    classNames?: Array<string>;
    editable?: boolean;
    display?: string;
    backgroundColor?: string;
    extendedProps?: any;
}