/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgencyModel } from './agencyModel';
import { BulletinModel } from './bulletinModel';
import { HomeworkModel } from './homeworkModel';
import { LessonPlanModel } from './lessonPlanModel';
import { PersonModel } from './personModel';

export interface DirectoryModel { 
    id?: string;
    parentId?: string;
    name: string;
    _private?: boolean;
    staffOnly?: boolean;
    parent?: DirectoryModel;
    bulletin?: BulletinModel;
    homeworkItem?: HomeworkModel;
    person?: PersonModel;
    lessonPlan?: LessonPlanModel;
    agency?: AgencyModel;
}