/**
 * MyPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DirectoryModel } from './directoryModel';
import { DocumentTypeModel } from './documentTypeModel';
import { FileModel } from './fileModel';
import { HomeworkSubmissionModel } from './homeworkSubmissionModel';
import { UserModel } from './userModel';

export interface DocumentModel { 
    id?: string;
    typeId?: string;
    directoryId?: string;
    title: string;
    description?: string;
    createdById?: string;
    createdDate?: Date;
    restricted?: boolean;
    deleted?: boolean;
    createdBy?: UserModel;
    directory?: DirectoryModel;
    type?: DocumentTypeModel;
    homeworkSubmission?: HomeworkSubmissionModel;
    attachment?: FileModel;
}