/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StudentModel } from './studentModel';

export interface ExamCandidateModel { 
    id?: string;
    studentId?: string;
    uci?: string;
    candidateNumber?: string;
    previousCandidateNumber?: string;
    previousCentreNumber?: string;
    specialConsideration?: boolean;
    note?: string;
    student?: StudentModel;
}