/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StudentModel } from './studentModel';
import { SubjectModel } from './subjectModel';

export interface GiftedTalentedModel { 
    id?: string;
    studentId?: string;
    subjectId?: string;
    notes: string;
    student?: StudentModel;
    subject?: SubjectModel;
}