/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DirectoryModel } from './directoryModel';

export interface HomeworkModel { 
    id?: string;
    directoryId?: string;
    title?: string;
    description?: string;
    submitOnline?: boolean;
    directory?: DirectoryModel;
}