/**
 * MyPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DirectoryModel } from './directoryModel';
import { EthnicityModel } from './ethnicityModel';
import { PhotoModel } from './photoModel';

export interface PersonModel { 
    id?: string;
    directoryId?: string;
    title?: string;
    firstName: string;
    middleName?: string;
    lastName: string;
    chosenFirstName?: string;
    photoId?: string;
    nhsNumber?: string;
    updatedDate?: Date;
    gender: string;
    dob?: Date;
    deceased?: Date;
    ethnicityId?: string;
    deleted?: boolean;
    directory?: DirectoryModel;
    photo?: PhotoModel;
    ethnicity?: EthnicityModel;
}