/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PersonModel } from './personModel';
import { PersonTypeIndicator } from './personTypeIndicator';

export interface PersonSearchResultModel { 
    person?: PersonModel;
    personTypes?: PersonTypeIndicator;
}