/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StaffMemberModel } from './staffMemberModel';
import { YearGroupModel } from './yearGroupModel';

export interface RegGroupModel { 
    id?: string;
    name: string;
    tutorId?: string;
    yearGroupId?: string;
    tutor?: StaffMemberModel;
    yearGroup?: YearGroupModel;
}