/**
 * MyPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExamCandidateModel } from './examCandidateModel';
import { HouseModel } from './houseModel';
import { PersonModel } from './personModel';
import { RegGroupModel } from './regGroupModel';
import { SenStatusModel } from './senStatusModel';
import { YearGroupModel } from './yearGroupModel';

export interface StudentModel { 
    id?: string;
    personId?: string;
    regGroupId?: string;
    yearGroupId?: string;
    houseId?: string;
    admissionNumber?: number;
    dateStarting?: Date;
    dateLeaving?: Date;
    freeSchoolMeals?: boolean;
    senStatusId?: string;
    pupilPremium?: boolean;
    upn?: string;
    deleted?: boolean;
    regGroup?: RegGroupModel;
    yearGroup?: YearGroupModel;
    person?: PersonModel;
    candidate?: ExamCandidateModel;
    senStatus?: SenStatusModel;
    house?: HouseModel;
}