/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type StudentStatus = 0 | 1 | 2 | 3;

export const StudentStatus = {
    NUMBER_0: 0 as StudentStatus,
    NUMBER_1: 1 as StudentStatus,
    NUMBER_2: 2 as StudentStatus,
    NUMBER_3: 3 as StudentStatus
};