/**
 * MyPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HomeworkSubmissionModel } from './homeworkSubmissionModel';
import { PersonModel } from './personModel';
import { TaskTypeModel } from './taskTypeModel';
import { UserModel } from './userModel';

export interface TaskModel { 
    id?: string;
    typeId?: string;
    assignedToId?: string;
    assignedById?: string;
    createdDate?: Date;
    dueDate?: Date;
    completedDate?: Date;
    title: string;
    description?: string;
    completed?: boolean;
    homeworkSubmission?: HomeworkSubmissionModel;
    assignedTo?: PersonModel;
    assignedBy?: UserModel;
    type?: TaskTypeModel;
    readonly overdue?: boolean;
}