/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TreeNodeState } from './treeNodeState';

export interface TreeNode { 
    id?: string;
    text?: string;
    icon?: string;
    state?: TreeNodeState;
    children?: Array<TreeNode>;
}