/**
 * MyPortal
 * MyPortal Master Web Service
 *
 * OpenAPI spec version: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurriculumYearGroupModel } from './curriculumYearGroupModel';
import { StaffMemberModel } from './staffMemberModel';

export interface YearGroupModel { 
    id?: string;
    name: string;
    headId?: string;
    curriculumYearGroupId?: string;
    headOfYear?: StaffMemberModel;
    curriculumYearGroup?: CurriculumYearGroupModel;
}